watch:
  directories:
    - app
    - database
    - tests
    - resources
    - routes
  fileMask: '*.php'
phpunit:
  binaryPath: vendor/bin/phpunit
  arguments: '--order-by=defects --stop-on-failure --cache-result'
